services:
  - type: web
    name: newsbulletin
    env: node
    buildCommand: npm install && npm run build && sleep 10 && npm run migrate && sleep 5 && npm run seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false 